language: node_js
node_js:
    - 8.11.4
    - 10.9.0
sudo: false

notifications:
    email:
        - guiltyrage10@gmail.com
branches:
    only:
        - master
install:
    - npm install -g grunt-cli
    - npm install
script:
    - npm run lint
    - npm test
after_script:
    - bash <(curl -s https://codecov.io/bash)
