language: node_js
node_js:
    - 4.2.3
sudo: false

notifications:
    email:
        - heinrich@aftership.net
branches:
    only:
        - master
install:
    - npm install -g grunt-cli
    - npm install
script:
    - npm run lint
    - npm test
after_script:
    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN > /dev/null
